# Generated by Django 5.1 on 2025-07-21 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('couleur', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.categorie')),
            ],
        ),
    ]
