# Generated by Django 5.1 on 2025-07-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('couleur', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paye', models.BooleanField(default=False, verbose_name='Payée')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.categorie')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.client', verbose_name='Client')),
            ],
        ),
    ]
