# Generated by Django 5.1 on 2025-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Montant TTC'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Montant TVA'),
        ),
    ]
