# Generated by Django 5.1 on 2025-07-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='paye',
            field=models.BooleanField(default=False, verbose_name='Payée'),
        ),
    ]
